// Generated by Wrangler on Tue May 28 2024 23:00:26 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  tadpole: KVNamespace;
  DB: D1Database;
}
